#!/usr/bin/env node

const child_process = require('child_process');

const exec = async (cmd, cwd = __dirname) => {
  return new Promise((resolve, reject) => {
    child_process.exec(cmd, { cwd }, (error, stdout, stderr) => {
      if (error) reject(new Error(`exec error ${error}: ${stderr}`));
      resolve(stdout);
    });
  });
};

try {
  (async () => {
    await exec('npm run compile');

    const generator = require('./build/tests/generator');

    let use = 'dmg';
    const argv = process.arv.slice(2);
    if (['calc', 'smogon'].includes(argv[0])) {
      use = 'calc';
      argv.shift();
    } else if (args[0] === 'dmg') {
      argv.shift();
    }

    console.log(generator.generate(argv.join(' '), use));
  })();
} catch (e) {
  console.error(e.message);
  process.exit(1);
}

